source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'meta_search', :git => 'git://github.com/ernie/meta_search.git', :ref => '7bf339d'
gem 'kaminari'
gem 'formtastic'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Asset template engines
gem 'json'
gem 'sass'
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

